require "paq" {
    "mfussenegger/nvim-lint";
    "mhartington/formatter.nvim";
    "hrsh7th/cmp-nvim-lsp";
    "hrsh7th/cmp-buffer";
    "hrsh7th/cmp-path";
    "hrsh7th/cmp-cmdline";
    "hrsh7th/nvim-cmp";
    "antoinemadec/FixCursorHold.nvim";
    --"nvim-neotest/neotest";
    --"nvim-neotest/neotest-python";
    "tpope/vim-fugitive";
    "lewis6991/gitsigns.nvim";
    "nvim-lua/plenary.nvim";
    {"nvim-telescope/telescope.nvim", branch="0.1.x"};
    {"embark-theme/vim", as="embark"};
    {"akinsho/bufferline.nvim", tag="v3.*"};
    "mfussenegger/nvim-dap";
    "mfussenegger/nvim-dap-python";
    "rcarriga/nvim-dap-ui";
    "folke/tokyonight.nvim";
    "nvim-lualine/lualine.nvim";
    "arkav/lualine-lsp-progress";
    "kyazdani42/nvim-web-devicons";
    "junegunn/goyo.vim";
    "Kjwon15/vim-transparent";
    "scrooloose/nerdcommenter";
    "mhinz/vim-startify";
    "scrooloose/nerdtree";
    "Xuyuanp/nerdtree-git-plugin";
    "williamboman/mason.nvim";
    "williamboman/mason-lspconfig.nvim";
    "neovim/nvim-lspconfig";
    "bling/vim-bufferline";
    {"nvim-treesitter/nvim-treesitter", build=":TSUpdate"};
    "github/copilot.vim";
}
