#!/bin/bash

B='#1b181bff'  # bg
C='#cbd6e2ff'  # clear ish
D='#ffffffff'  # default
T='#cbd6e2cc'  # text
W='#880000ff'  # wrong
V='#223b54ff'  # verifying

i3lock              \
--insidevercolor=$B   \
--ringvercolor=$V   \
\
--insidewrongcolor=$B \
--ringwrongcolor=$B   \
\
--insidecolor=$B      \
--ringcolor=$B        \
--linecolor=$B        \
--separatorcolor=$T   \
\
--textcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--keyhlcolor=$T       \
--bshlcolor=$T        \
-c "#1b181b" \
--screen 0            \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %d.%m.%Y" \
--wrongtext="!" \
--veriftext="..." \
--timesize=32 \
--datesize=14 \
--radius=80  \
--blur 0 \
--timefont="Iosevka Term" \
--datefont="Iosevka Term" \
# etc
