#!/bin/sh

B='#1b181bff'  # bg
C='#cbd6e2ff'  # clear ish
D='#ffffffff'  # default
T='#cbd6e2cc'  # text
W='#880000ff'  # wrong
V='#bb00bbff'  # verifying

$HOME/.local/opt/bin/i3lock              \
--insidevercolor=$B   \
--ringvercolor=$V   \
\
--insidewrongcolor=$W \
--ringwrongcolor=$W   \
\
--insidecolor=$B      \
--ringcolor=$B        \
--linecolor=$B        \
--separatorcolor=$T   \
\
--textcolor=$T        \
--timecolor=$T        \
--datecolor=$T        \
--keyhlcolor=$T       \
--bshlcolor=$T        \
-c "#1b181b" \
--screen 1            \
--clock               \
--indicator           \
--timestr="%H:%M:%S"  \
--datestr="%A, %d.%m.%Y" \
--wrongtext="!" \
--veriftext="..." \
--timesize=32 \
--datesize=14 \
--radius=120  \
--blur 0 \
--timefont="Input Mono Compressed" \
--datefont="Input Mono Compressed"
# etc
