live_config_reload = true
import = ["~/.config/alacritty/themes/themes/cyberdream.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 1

[cursor]
style = "Beam"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
COLORTERM = "truecolor"
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1.5"

[font]
size = 9
[font.bold]
family = "Alacritty"
style = "Bold"

[font.glyph_offset]
x = 0
y = 3

[font.normal]
family = "Alacritty"
style = "Regular"

[font.offset]
x = 1
y = 6

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
opacity = 0.8
dynamic_padding = false

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 10
y = 10
